In [48]:
import wave

# Create audio file with wave object
good_morning = wave.open("good-morning.wav", 'r')

# Read all frames from wave object
soundwave_gm = good_morning.readframes(-1)

print(soundwave_gm[:1000])
    # b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

len(soundwave_gm)
    # 221184
    # as file size 216KB
    # 216KB = 216*1024 = 221184B


b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

221184

## Converting Sound Wave Bytes to Integer

In [51]:
# Converting bytes to integer

import wave
import numpy as np

good_morning = wave.open("good-morning.wav", 'r')
signal_gm = good_morning.readframes(-1)

# convert signal_gm from bytes to integers
soundwave_gm = np.frombuffer(signal_gm, dtype="int16")
    # len - 110592 (half of the len(signal_gm))

soundwave_gm[51000:51010]
    # [-275 -273 -271 -276 -284 -276 -269 -282 -291 -292]



array([-275, -273, -271, -276, -284, -276, -269, -282, -291, -292],
      dtype=int16)

In [52]:
# Finding FrameRate
framerate_gm = good_morning.getframerate()
framerate_gm
    # 44100 (in hz)


# Finding number of frames (both same)
num_frames = good_morning.getnframes()
num_frames = len(soundwave_gm)
num_frames
    # 110592


# Duration of audio file (seconds) = number of frames/frequency (Hz)
duration = num_frames/framerate_gm
duration 
    # 2.507755102040816 (in seconds)


# Get timestamps
timestamps_gm = np.linspace(start = 0, stop = duration , num = num_frames)
timestamps_gm[:10]
"""
   array([0.00000000e+00, 1.13379197e-05, 2.26758395e-05, 3.40137592e-05,
          4.53516790e-05, 5.66895987e-05, 6.80275184e-05, 7.93654382e-05,
          9.07033579e-05, 1.02041278e-04])
"""


'\n   array([0.00000000e+00, 1.13379197e-05, 2.26758395e-05, 3.40137592e-05,\n          4.53516790e-05, 5.66895987e-05, 6.80275184e-05, 7.93654382e-05,\n          9.07033579e-05, 1.02041278e-04])\n'